package de.ruu.app.jeeeraaah.client.fx.taskgroup.editor;

import de.ruu.app.jeeeraaah.client.fx.taskgroup.mapstruct.TaskGroupFXBean;
import de.ruu.lib.fx.comp.FXCViewService;
import lombok.NonNull;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.10.12 12:36:45:058
 */
public interface TaskGroupEditorService extends FXCViewService
{
	@NonNull Optional<TaskGroupFXBean> taskGroup();
	void taskGroup(@NonNull TaskGroupFXBean taskGroupFXBean);
}