package de.ruu.app.jeeeraaah.client.fx.taskgroup.editor;

import de.ruu.app.jeeeraaah.client.fx.taskgroup.mapstruct.TaskGroupFXBean;
import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

import java.util.Optional;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.10.12 12:36:45:059
 */
@Slf4j
class TaskGroupEditorController extends DefaultFXCViewController implements TaskGroupEditorService
{
	@NonNull private TaskGroupFXBean taskGroup;

	@FXML private AnchorPane root;

	@FXML private Label     lblName;
	@FXML private TextField tfName;

	@FXML private Label     lblDescription;
	@FXML private TextArea  tAreaDescription;

	@Override @FXML protected void initialize()
	{
		tfName.requestFocus();
	}

	@Override public @NonNull Optional<TaskGroupFXBean> taskGroup() { return Optional.of(taskGroup); }

	@Override public void taskGroup(@NonNull TaskGroupFXBean taskGroupFXBean)
	{
		taskGroup = taskGroupFXBean;
		// bind properties of fx controls to properties of taskGroup
		taskGroup.nameProperty       ().bind(tfName          .textProperty());
		taskGroup.descriptionProperty().bind(tAreaDescription.textProperty());
	}
}