package de.ruu.app.jeeeraaah.client.fx.taskgroup.editor;

import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCViewService;

/**
 * Java FX Component {@link TaskGroupEditor}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.10.12 12:36:45:056
 */
public class TaskGroupEditor extends DefaultFXCView
{
	@Override public TaskGroupEditorService getService()
	{
		FXCViewService service = super.getService();

		if (service instanceof TaskGroupEditorService) return (TaskGroupEditorService) service;

		throw new IllegalStateException(
				  "unexpected service type " + service.getClass().getName()
				+ ", expected " + TaskGroupEditorService.class.getName());
	}
}