package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.app.jeeeraaah.client.fx.taskgroup.mapstruct.TaskFXBean;
import de.ruu.lib.fx.comp.FXCViewService;
import lombok.NonNull;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.09.27 16:54:05:943
 */
public interface TaskViewService extends FXCViewService
{
	@NonNull Optional<TaskFXBean> task();
	void task(@NonNull TaskFXBean task);
}