package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskViewApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.09.27 16:54:05:953
 */
public class TaskViewApp extends FXCApp
{
}