package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskViewAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.09.27 16:54:05:957
 */
@Slf4j class TaskViewAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting TaskViewAppRunner.class.getName()");

		// force class to be loaded (and it's static initialiser to be executed)
		// add-reads module of FXCAppStartedEvent to ALL-UNNAMED
		Class<?> clazz = Class.forName(FXCAppStartedEvent.class.getName());
		log.debug("loaded {}", clazz.getName());

		FXCAppRunner.run(TaskViewApp.class, args);
		log.debug("finished TaskViewAppRunner.class.getName()");
	}
}