package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.09.27 16:54:05:943
 */
public interface TaskViewService extends FXCViewService { }