package de.ruu.app.jeeeraaah.common.jpa;

import de.ruu.app.jeeeraaah.common.Task;
import de.ruu.app.jeeeraaah.common.dto.TaskGroupEntityDTO;
import de.ruu.app.jeeeraaah.common.jpadto.Mapper;
import de.ruu.app.jeeeraaah.common.jpadto.TaskEntity;
import de.ruu.app.jeeeraaah.common.jpadto.TaskGroupEntity;
import de.ruu.lib.jpa.core.mapstruct.AbstractMappedEntity;
import de.ruu.lib.util.Strings;
import jakarta.annotation.Nullable;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import lombok.extern.slf4j.Slf4j;

import java.util.Collections;
import java.util.HashSet;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import static java.util.Objects.isNull;

@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Slf4j
@Getter                   // generate getter methods for all fields using lombok unless configured otherwise ({@code
@Setter                   // generate setter methods for all fields using lombok unless configured otherwise ({@code
@Accessors(fluent = true) // generate fluent accessors with lombok and java-bean-style-accessors in non-abstract classes
                          // with ide, fluent accessors will (usually / by default) be ignored by mapstruct
@RequiredArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true) // generate no args constructor for jsonb, jaxb, jpa, mapstruct, ...
@Entity
@Table(schema = "app_jeeeraaah_test", name = "task_group")
public class TaskGroupEntityJPA
		extends AbstractMappedEntity<TaskGroupEntityDTO>
		implements TaskGroupEntity<TaskEntityJPA>
{
	/** mutable non-null */
	// no lombok-generation of setter because of additional validation in manually created method
	@Setter(AccessLevel.NONE)
	@Column(unique=true, nullable=false)
	@NonNull private String name;

	/** mutable nullable */
	@Nullable private String description;

	/**
	 * prevent direct access to this modifiable set from outside this class, use {@link #addTask(TaskEntityJPA)} and
	 * {@link #removeTask(TaskEntityJPA)} to modify the set
	 * <p>
	 * may explicitly be {@code null}, {@code null} indicates that there was no attempt to load related objects from db
	 * (lazy)
	 */
	@Nullable
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@Getter(AccessLevel.NONE) // provide handmade getter that returns unmodifiable
	@Setter(AccessLevel.NONE) // no setter at all
	@OneToMany
	(
			mappedBy = TaskEntityJPA_.TASK_GROUP,
			// do not use cascade REMOVE in to-many relations as this may result in cascading deletes that wipe out both sides
			// of the relation entirely
			cascade  = { CascadeType.PERSIST, CascadeType.MERGE }
	)
	private Set<TaskEntityJPA> tasks;

	protected TaskGroupEntityJPA(@NonNull de.ruu.lib.jpa.core.Entity<Long> entity) { super(entity); }

	////////////////////////////////////////////////////////////////////////
	// fluent style accessors generated by lombok if not specified otherwise
	////////////////////////////////////////////////////////////////////////

	/**
	 * manually created fluent setter with extra parameter check (see throws documentation)
	 * @param name non-null, non-empty, non-blank
	 * @return {@code this}
	 * @throws IllegalArgumentException if {@code name} parameter is empty or blank
	 * @throws NullPointerException     if {@code name} parameter is {@code null}
	 */
	@NonNull public TaskGroupEntityJPA name(@NonNull String name)
	{
		if (Strings.isEmptyOrBlank(name)) throw new IllegalArgumentException("name must not be empty nor blank");
		this.name = name;
		return this;
	}

	@Override @NonNull public Optional<String> description() { return Optional.ofNullable(description); }

	/** @return {@link #tasks} wrapped in unmodifiable */
	@Override @NonNull public Optional<Set<TaskEntityJPA>> tasks()
	{
		if (Objects.isNull(tasks)) return Optional.empty();
		return Optional.of(Collections.unmodifiableSet(tasks));
	}

	///////////////////////
	// additional accessors
	///////////////////////

	@Override public void beforeMapping(@NonNull TaskGroupEntityDTO input) { }
	@Override public void afterMapping (@NonNull TaskGroupEntityDTO input) { }

	@Override public @NonNull TaskGroupEntityDTO toTarget()
	{
		return Mapper.INSTANCE.map(this);
	}

	////////////////////////
	// relationship handling
	////////////////////////
	/**
	 * @param entity the {@link Task} to be added as task
	 * @return {@code this}
	 * @throws IllegalStateException if {@code entity} could not be removed from {@link #tasks}
	 */
	public boolean addTask(@NonNull TaskEntityJPA entity)
	{
		// update bidirectional relation
		if (nonNullTasks().add(entity))
		{
			entity.taskGroup(this);
			return true;
		}

		throw new IllegalStateException("could not add task entity");
	}

	@Override public boolean removeTask(@NonNull TaskEntityJPA entity)
	{
		return tasks().map(ts -> ts.remove(entity)).orElse(false);
	}

	//////////////////////////////////////////////////////////////////////////////////////////////
	// java bean style accessors for those who do not work with fluent style accessors (mapstruct)
	//////////////////////////////////////////////////////////////////////////////////////////////
	@NonNull
	public String getName()                     { return name(); }
	public void   setName(@NonNull String name) { name(name); }

	public String getDescription()                   { return description().orElse(null); }
	public void   setDescription(String description) { description(description); }
	// do _NOT_ define getter for tasks to avoid handling of tasks by mapstruct automatism

	private Set<TaskEntityJPA> nonNullTasks()
	{
		if (isNull(tasks)) tasks = new HashSet<>();
		return tasks;
	}
}