package de.ruu.app.jeeeraaah.common;

import de.ruu.lib.jpa.core.mapstruct.AbstractMappedEntity;
import de.ruu.lib.util.Strings;
import jakarta.annotation.Nullable;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import lombok.extern.slf4j.Slf4j;

import java.util.*;

import static java.util.Objects.isNull;
import static lombok.AccessLevel.PROTECTED;

@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Slf4j
@Getter                   // generate getter methods for all fields using lombok unless configured otherwise ({@code
// @Getter(AccessLevel.NONE}))
@Setter                   // generate setter methods for all fields using lombok unless configured otherwise ({@code
// @Setter(AccessLevel.NONE}))
@Accessors(fluent = true) // generate fluent accessors with lombok and java-bean-style-accessors in non-abstract classes
// with ide, fluent accessors will (usually / by default) be ignored by mapstruct
@RequiredArgsConstructor
@NoArgsConstructor(access = PROTECTED, force = true) // generate no args constructor for jsonb, jaxb, jpa, mapstruct, ...
@Entity
@Table(schema = "app_test", name = "task_group")
public class TaskGroupEntity extends AbstractMappedEntity<TaskGroupDTO> implements TaskGroup
{
	/** mutable non-null */
	// no lombok-generation of setter because of additional validation in manually created method
	@NonNull
	@Setter(AccessLevel.NONE)
	@Column(unique=true, nullable=false)
	private String name;

	/**
	 * prevent direct access to this modifiable set from outside this class, use {@link #addTask(TaskEntity)} and
	 * {@link #removeTask(TaskEntity)} to modify the set
	 * <p>
	 * may explicitly be {@code null}, {@code null} indicates that there was no attempt to load related objects from db
	 * (lazy)
	 */
	@Nullable
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@Getter(AccessLevel.NONE) // provide handmade getter that returns unmodifiable
	@Setter(AccessLevel.NONE) // no setter at all
	@OneToMany
	(
			mappedBy = TaskEntity_.TASK_GROUP,
			// do not use cascade REMOVE in to-many relations as this may result in cascading deletes that wipe out both sides
			// of the relation entirely
			cascade  = { CascadeType.PERSIST, CascadeType.MERGE }
	)
	private Set<TaskEntity> tasks;

	////////////////////////////////////////////////////////////////////////
	// fluent style accessors generated by lombok if not specified otherwise
	////////////////////////////////////////////////////////////////////////
	/**
	 * manually created fluent setter with extra parameter check (see throws documentation)
	 * @param name non-null, non-empty, non-blank
	 * @return {@code this}
	 * @throws IllegalArgumentException if {@code name} parameter is empty or blank
	 * @throws NullPointerException     if {@code name} parameter is {@code null}
	 */
	@NonNull
	public TaskGroupEntity name(@NonNull String name)
	{
		if (Strings.isEmptyOrBlank(name)) throw new IllegalArgumentException("name must not be empty nor blank");
		this.name = name;
		return this;
	}

	/** @return {@link #tasks} wrapped in unmodifiable */
	@Override
	@NonNull
	public Optional<Set<? extends Task>> tasks()
	{
		Optional<Set<TaskEntity>> tasks = optionalTasks();
		if (tasks.isPresent())
				return Optional.of(Collections.unmodifiableSet(tasks.get()));
		return Optional.empty();
	}

	///////////////////////
	// additional accessors
	///////////////////////
	/** @return optional unmodifiable */
	public Optional<Set<TaskEntity>> optionalTasks()
	{
		if (Objects.isNull(tasks)) return Optional.empty();
		return Optional.of(Collections.unmodifiableSet(tasks));
	}

	//////////////////////////////////////////////////////////////////////////////////////////////
	// java bean style accessors for those who do not work with fluent style accessors (mapstruct)
	//////////////////////////////////////////////////////////////////////////////////////////////
	public @NonNull String getName() { return name(); }
	// do _NOT_ define getter for tasks to avoid handling of tasks by mapstruct automatism

	@Override
	public void afterMapping(@NonNull TaskGroupDTO input) { }

	@Override
	public @NonNull TaskGroupDTO toTarget()
	{
		return Mapper.INSTANCE.map(this);
	}

	////////////////////////
	// relationship handling
	////////////////////////
	/**
	 * @param entity the {@link Task} to be added as task
	 * @return {@code this}
	 * @throws IllegalStateException if {@code entity} could not be removed from {@link #tasks}
	 */
	@NonNull
	public TaskGroupEntity addTask(@NonNull TaskEntity entity)
	{
		// update bidirectional relation
		if (nonNullTasks().add(entity))
		{
			entity.taskGroup(this);
			return this;
		}

		throw new IllegalStateException("could not add task entity");
	}

	public boolean removeTask(@NonNull TaskEntity entity)
	{
		if (optionalTasks().isPresent())
				return optionalTasks().get().remove(entity);
		return false;
	}

	private Set<TaskEntity> nonNullTasks()
	{
		if (isNull(tasks)) tasks = new HashSet<>();
		return tasks;
	}
}