package de.ruu.app.demo.common.datamodel.dto;

import de.ruu.app.demo.common.Company;
import de.ruu.app.demo.common.Department;
import de.ruu.app.demo.common.datamodel.Mapper;
import de.ruu.app.demo.common.datamodel.jpa.CompanyEntity;
import de.ruu.lib.jpa.core.mapstruct.AbstractMappedDTO;
import de.ruu.lib.util.Strings;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import lombok.extern.slf4j.Slf4j;

import java.util.Collections;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

import static java.util.Objects.isNull;
import static lombok.AccessLevel.NONE;
import static lombok.AccessLevel.PROTECTED;

@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Slf4j
@Getter                   // generate getter methods for all fields using lombok unless configured otherwise ({@code
                          // @Getter(AccessLevel.NONE}))
@Accessors(fluent = true) // generate fluent accessors with lombok and java-bean-style-accessors in non-abstract classes
                          // with ide, fluent accessors will (usually / by default) be ignored by mapstruct
@RequiredArgsConstructor
@NoArgsConstructor(access = PROTECTED, force = true) // generate no args constructor for jsonb, jaxb, mapstruct, ...
public class CompanyDTO extends AbstractMappedDTO<CompanyEntity> implements Company
{
	/** mutable non-null */
	// no lombok-generation of setter because of additional validation in manually created method
	@NonNull
	@Setter(NONE)
	private String name;

	/**
	 * prevent direct access to nullable modifiable set from outside
	 * may explicitly be {@code null}, {@code null} indicates that there was no attempt to load related objects from db
	 * (lazy)
	 */
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@Getter(NONE)
	private Set<DepartmentDTO> departments;

	@Override public void beforeMapping(@NonNull CompanyEntity input)
	{
		super.beforeMapping(input);
		if (input.optionalDepartments().isPresent())
				input.optionalDepartments().get().forEach(d -> add(d.toTarget()));
		name(input.name());
	}

	@Override public void afterMapping(@NonNull CompanyEntity input)
	{
		log.debug("after mapping starting");
		log.debug("after mapping finished");
	}

	@Override public @NonNull CompanyEntity toSource() { return Mapper.INSTANCE.map(this); }

	// java bean style accessors for those who do not work with fluent style accessors (mapstruct)
	@NonNull
	public String getName() { return name(); }

	// not generated by lombok because of extra parameter validation
	@Override public @NonNull Company name(@NonNull String name)
	{
		if (Strings.isEmptyOrBlank(name)) throw new IllegalArgumentException("name must not be empty nor blank");
		this.name = name;
		return this;
	}

	/** return optional unmodifiable */
	@Override public Optional<Set<Department>> departments()
	{
		// return unmodifiable set of interface type instead of set of DTO2 types
		Optional<Set<DepartmentDTO>> optionalDepartments = optionalDepartments();
		if (optionalDepartments.isPresent()) return Optional.of(new HashSet<>(optionalDepartments.get()));
		return Optional.empty();
	}

	/** return optional unmodifiable */
	public Optional<Set<DepartmentDTO>> optionalDepartments()
	{
		if (isNull(departments)) return Optional.empty();
		return Optional.of(Collections.unmodifiableSet(departments));
	}

	public boolean add(@NonNull DepartmentDTO department)
	{
		if (department.company() == this)
		{
			if (departmentsContains(department)) return true;
			return nonNullDepartments().add(department);
		}
		else
		{
			// following check should never return true
			if (departmentsContains(department))
					log.error("department with {} is already contained in {}", department.company(), this);

			// assign this department as department of department and update employees
			department.company(this);
			return nonNullDepartments().add(department);
		}
	}

	public boolean remove(@NonNull DepartmentDTO dto)
	{
		if (isNull(departments)) return false;
		return departments.remove(dto);
	}

	private Set<DepartmentDTO> nonNullDepartments()
	{
		if (isNull(departments)) departments = new HashSet<>();
		return departments;
	}

	private boolean departmentsContains(DepartmentDTO dto)
	{
		if (isNull(departments)) return false;
		return departments.contains(dto);
	}
}