package de.ruu.app.jeeeraaah.client.fx.task;

import de.ruu.app.jeeeraaah.common.Task;
import de.ruu.app.jeeeraaah.common.TaskGroup;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.time.Duration;
import java.time.LocalDate;
import java.util.Optional;
import java.util.Set;

/**
 * JavaBean {@link TaskBean}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.bean.BeanGenerator} at 2024.09.22 16:44:27:044
 */
@AllArgsConstructor
@Builder(toBuilder = true)
public class TaskBean implements Task
{
	private LocalDate finishActual;
	private Optional<LocalDate> finishEstimatedOptional;
	private Optional<Task> optionalParent;
	private Optional<String> descriptionOptional;
	private Optional<LocalDate> startEstimatedOptional;
	private TaskGroup taskGroup;
	private LocalDate startActual;
	private Optional<LocalDate> finishActualOptional;
	private Duration effortActual;
	private LocalDate startEstimated;
	private Optional<LocalDate> startActualOptional;
	private Optional<Set<Task>> successors;
	private Optional<Set<? extends Task>> children;
	private Optional<Duration>            effortActualOptional;
	private Long                          id;
	private String                        description;
	private LocalDate                     finishEstimated;
	private Optional<Set<Task>>           predecessors;
	private String name;
	
	public Optional<Set<? extends Task>> children()
	{
		return children;
	}
	
	public String description()
	{
		return description;
	}
	
	public Optional<String> descriptionOptional()
	{
		return descriptionOptional;
	}
	
	public Duration effortActual()
	{
		return effortActual;
	}
	
	public Optional<Duration> effortActualOptional()
	{
		return effortActualOptional;
	}
	
	public LocalDate finishActual()
	{
		return finishActual;
	}
	
	public Optional<LocalDate> finishActualOptional()
	{
		return finishActualOptional;
	}
	
	public LocalDate finishEstimated()
	{
		return finishEstimated;
	}
	
	public Optional<LocalDate> finishEstimatedOptional()
	{
		return finishEstimatedOptional;
	}
	
	public Long id()
	{
		return id;
	}
	
	public String name()
	{
		return name;
	}
	
	public Optional<Task> optionalParent()
	{
		return optionalParent;
	}
	
	public Optional<Set<Task>> predecessors()
	{
		return predecessors;
	}
	
	public LocalDate startActual()
	{
		return startActual;
	}
	
	public Optional<LocalDate> startActualOptional()
	{
		return startActualOptional;
	}
	
	public LocalDate startEstimated()
	{
		return startEstimated;
	}
	
	public Optional<LocalDate> startEstimatedOptional()
	{
		return startEstimatedOptional;
	}
	
	public Optional<Set<Task>> successors()
	{
		return successors;
	}
	
	public TaskGroup taskGroup()
	{
		return taskGroup;
	}
}