package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link PostalAddressManager}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.07.16 17:31:37:428
 */
public class PostalAddressManager extends DefaultFXCView
{
}