package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link PostalAddressManagerAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.07.16 17:31:37:497
 */
@Slf4j
class PostalAddressManagerAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", PostalAddressManagerAppRunner.class.getName());
		FXCAppRunner.run(PostalAddressManagerApp.class, args);
		log.debug("finished {}", PostalAddressManagerAppRunner.class.getName());
	}
}