package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.app.demo.client.datamodel.rs.postaladdress.ClientPostalAddress;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.DefaultFXCViewController;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.control.TableViewConfig;
import de.ruu.lib.fx.css.ButtonUtil;
import de.ruu.lib.fx.css.Color;
import de.ruu.lib.fx.css.FontWeight;
import jakarta.inject.Inject;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TableView;
import javafx.scene.control.ToolBar;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import lombok.extern.slf4j.Slf4j;

import java.util.Optional;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.07.16 17:31:37:465
 */
@Slf4j
class PostalAddressManagerController extends DefaultFXCViewController
{
	@FXML private Button btnAdd;
	@FXML private Button btnRemove;
	@FXML private ImageView ivwAdd;
	@FXML private ImageView ivwRemove;
	@FXML private AnchorPane root;
	@FXML private ToolBar tbr;
	@FXML private TableView<PostalAddressFXBean> tv;
	@FXML private VBox vbx;

	@Inject private ClientPostalAddress client;

	@Inject private EventDispatcher<FXCAppStartedEvent> eventDispatcherFXCAppStarted;

	@Override @FXML
	protected void initialize()
	{
		PostalAddressFXTableViewConfigurator.configure(tv);

		client.findAll().forEach(address -> tv.getItems().add(new PostalAddressFXBean(address)));

		eventDispatcherFXCAppStarted.add(e -> onAppStarted(e));
	}

	private void onAppStarted(FXCAppStartedEvent e)
	{
		Optional<Stage> optional = FXUtil.getStage(root);

		if (optional.isPresent())
		{
			optional.get().setTitle("postal address manager");
		}

//		Color.WHITE;
//		log.debug("before: {}", btnRemove.getStyle());
//		btnRemove.setStyle("-fx-background-color: white");
//		log.debug("after : {}", btnRemove.getStyle());
		ButtonUtil.backgroundColor(btnRemove, Color.WHITE);

		TableViewConfig tableViewConfig = new TableViewConfig(tv);
		tableViewConfig.setColumnHeaderFontWeight(FontWeight.NORMAL);
	}
}