package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.app.datamodel.postaladdress.PostalAddress;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import lombok.Builder;
import lombok.RequiredArgsConstructor;

/**
 * FXBean {@link PostalAddressFXBean}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.bean.FXBeanGenerator} at 2024.07.17 11:36:09:281
 */
@RequiredArgsConstructor
@Builder
public class PostalAddressFXBean
{
	private StringProperty city;
	private StringProperty country;
	private StringProperty getCity;
	private StringProperty getCountry;
	private StringProperty getPostalCode;
	private StringProperty getStateOrProvince;
	private StringProperty getStreet;
	private StringProperty getStreetNumber;
	private StringProperty getType;
	private StringProperty postalCode;
	private StringProperty stateOrProvince;
	private StringProperty street;
	private StringProperty streetNumber;
	private StringProperty type;

	public PostalAddressFXBean(StringProperty city, StringProperty country, StringProperty getCity, StringProperty getCountry, StringProperty getPostalCode, StringProperty getStateOrProvince, StringProperty getStreet, StringProperty getStreetNumber, StringProperty getType, StringProperty postalCode, StringProperty stateOrProvince, StringProperty street, StringProperty streetNumber, StringProperty type)
	{
		this.city = city;
		this.country = country;
		this.getCity = getCity;
		this.getCountry = getCountry;
		this.getPostalCode = getPostalCode;
		this.getStateOrProvince = getStateOrProvince;
		this.getStreet = getStreet;
		this.getStreetNumber = getStreetNumber;
		this.getType = getType;
		this.postalCode = postalCode;
		this.stateOrProvince = stateOrProvince;
		this.street = street;
		this.streetNumber = streetNumber;
		this.type = type;
	}

	public PostalAddressFXBean(PostalAddress postalAddress)
	{
		city = new SimpleStringProperty(postalAddress.city());
		country = new SimpleStringProperty(postalAddress.country());
		getCity = new SimpleStringProperty(postalAddress.getCity());
		getCountry = new SimpleStringProperty(postalAddress.getCountry());
		getPostalCode = new SimpleStringProperty(postalAddress.getPostalCode());
		getStateOrProvince = new SimpleStringProperty(postalAddress.getStateOrProvince());
		getStreet = new SimpleStringProperty(postalAddress.getStreet());
		getStreetNumber = new SimpleStringProperty(postalAddress.getStreetNumber());
		getType = new SimpleStringProperty(postalAddress.getType());
		postalCode = new SimpleStringProperty(postalAddress.postalCode());
		stateOrProvince = new SimpleStringProperty(postalAddress.stateOrProvince());
		street = new SimpleStringProperty(postalAddress.street());
		streetNumber = new SimpleStringProperty(postalAddress.streetNumber());
		type = new SimpleStringProperty(postalAddress.type());
	}

	public StringProperty city()
	{
		return city;
	}

	public StringProperty country()
	{
		return country;
	}

	public StringProperty getCity()
	{
		return getCity;
	}

	public StringProperty getCountry()
	{
		return getCountry;
	}

	public StringProperty getPostalCode()
	{
		return getPostalCode;
	}

	public StringProperty getStateOrProvince()
	{
		return getStateOrProvince;
	}

	public StringProperty getStreet()
	{
		return getStreet;
	}

	public StringProperty getStreetNumber()
	{
		return getStreetNumber;
	}

	public StringProperty getType()
	{
		return getType;
	}

	public StringProperty postalCode()
	{
		return postalCode;
	}

	public StringProperty stateOrProvince()
	{
		return stateOrProvince;
	}

	public StringProperty street()
	{
		return street;
	}

	public StringProperty streetNumber()
	{
		return streetNumber;
	}

	public StringProperty type()
	{
		return type;
	}
}