package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link PostalAddressManagerApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.07.16 17:31:37:494
 */
public class PostalAddressManagerApp extends FXCApp
{
}