package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link PostalAddressManagerAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.07.16 17:31:37:497
 */
@Slf4j
class PostalAddressManagerAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", PostalAddressManagerAppRunner.class.getName());

		// force class to be loaded (and it's static initialiser to be executed)
		// add-reads module of FXCAppStartedEvent to ALL-UNNAMED
		Class<?> clazz = Class.forName(FXCAppStartedEvent.class.getName());
		log.debug("loaded {}", clazz.getName());

		FXCAppRunner.run(PostalAddressManagerApp.class, args);
		log.debug("finished {}", PostalAddressManagerAppRunner.class.getName());
	}
}