package de.ruu.app.demo.client.datamodel.fx.postaladdress;

import de.ruu.app.datamodel.postaladdress.PostalAddress;
import de.ruu.app.datamodel.postaladdress.dto.PostalAddressDTO;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import lombok.Builder;
import lombok.RequiredArgsConstructor;

/**
 * FXBean {@link PostalAddressFXBean}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.bean.FXBeanGenerator} at 2024.07.17 11:36:09:281
 */
@RequiredArgsConstructor
@Builder
public class PostalAddressFXBean
{
	private StringProperty street          = new SimpleStringProperty();
	private StringProperty streetNumber    = new SimpleStringProperty();
	private StringProperty postalCode      = new SimpleStringProperty();
	private StringProperty city            = new SimpleStringProperty();
	private StringProperty stateOrProvince = new SimpleStringProperty();
	private StringProperty country         = new SimpleStringProperty();
	private StringProperty type            = new SimpleStringProperty();

	public PostalAddressFXBean(
			StringProperty street,
			StringProperty streetNumber,
			StringProperty postalCode,
			StringProperty city,
			StringProperty stateOrProvince,
			StringProperty country,
			StringProperty type)
	{
		this.street          = street;
		this.streetNumber    = streetNumber;
		this.postalCode      = postalCode;
		this.city            = city;
		this.stateOrProvince = stateOrProvince;
		this.country         = country;
		this.type            = type;
	}

	public PostalAddressFXBean(PostalAddress postalAddress)
	{
		street          = new SimpleStringProperty(postalAddress.street());
		streetNumber    = new SimpleStringProperty(postalAddress.streetNumber());
		postalCode      = new SimpleStringProperty(postalAddress.postalCode());
		city            = new SimpleStringProperty(postalAddress.city());
		stateOrProvince = new SimpleStringProperty(postalAddress.stateOrProvince());
		country         = new SimpleStringProperty(postalAddress.country());
		type            = new SimpleStringProperty(postalAddress.type());
	}

	public PostalAddress toSource()
	{
		return
				new PostalAddressDTO(
						street         .getValue(),
						streetNumber   .getValue(),
						postalCode     .getValue(),
						city           .getValue(),
						stateOrProvince.getValue(),
						country        .getValue(),
						type           .getValue());
	}

	public StringProperty city()
	{
		return city;
	}

	public StringProperty country()
	{
		return country;
	}

	public StringProperty postalCode()
	{
		return postalCode;
	}

	public StringProperty stateOrProvince()
	{
		return stateOrProvince;
	}

	public StringProperty street()
	{
		return street;
	}

	public StringProperty streetNumber()
	{
		return streetNumber;
	}

	public StringProperty type()
	{
		return type;
	}
}