package de.ruu.app.demo.client.datamodel.fx.postaladdress;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.07.16 17:31:37:462
 */
public interface PostalAddressManagerService
{
}