package de.ruu.app.demo.client.datamodel.fx.postaladdress.edit;

import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCViewService;

/**
 * Java FX Component {@link PostalAddressFXBeanEditor}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.07.31 16:12:20:212
 */
public class PostalAddressFXBeanEditor extends DefaultFXCView
{
	@Override public PostalAddressFXBeanEditorService getService()
	{
		FXCViewService service = super.getService();

		if (service instanceof FXCViewService) return (PostalAddressFXBeanEditorService) service;

		throw new IllegalStateException(
				"unexpected service type " + service.getClass().getName()
						+ ", expected " + PostalAddressFXBeanEditorService.class.getName());
	}
}