package de.ruu.app.demo.client.datamodel.fx.postaladdress.edit;

import de.ruu.app.demo.client.datamodel.fx.postaladdress.PostalAddressFXBean;
import de.ruu.lib.fx.comp.FXCViewService;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.07.31 16:12:20:227
 */
public interface PostalAddressFXBeanEditorService extends FXCViewService
{
	Optional<PostalAddressFXBean> postalAddress();
	void postalAddress(PostalAddressFXBean postalAddress);
}