package de.ruu.app.demo.client.datamodel.fx.postaladdress.edit;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link PostalAddressFXBeanEditorApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.07.31 16:12:20:250
 */
public class PostalAddressFXBeanEditorApp extends FXCApp
{
}