package de.ruu.app.demo.client.datamodel.fx.postaladdress.edit;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link PostalAddressFXBeanEditorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.07.31 16:12:20:254
 */
@Slf4j class PostalAddressFXBeanEditorAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting PostalAddressFXBeanEditorAppRunner.class.getName()");
		FXCAppRunner.run(PostalAddressFXBeanEditorApp.class, args);
		log.debug("finished PostalAddressFXBeanEditorAppRunner.class.getName()");
	}
}