package de.ruu.app.jeeeraaah.client.fx.taskgroup.mapstruct;

import de.ruu.app.jeeeraaah.common.Task;
import de.ruu.app.jeeeraaah.common.dto.TaskEntityDTO;
import de.ruu.app.jeeeraaah.common.dto.TaskGroupEntityDTO;
import de.ruu.app.jeeeraaah.common.jpadto.TaskGroupEntity;
import de.ruu.lib.jpa.core.AbstractDTO;
import de.ruu.lib.jpa.core.AbstractEntity;
import de.ruu.lib.jpa.core.Entity;
import de.ruu.lib.util.Strings;
import jakarta.annotation.Nullable;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import lombok.extern.slf4j.Slf4j;
import org.mapstruct.AfterMapping;
import org.mapstruct.BeforeMapping;

import java.util.Collections;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

/** JavaBean for implementing business logic */
@EqualsAndHashCode
@ToString(callSuper = true)
@Slf4j
@Getter                   // generate getter methods for all fields using lombok unless configured otherwise ({@code
@Setter                   // generate setter methods for all fields using lombok unless configured otherwise ({@code
@Accessors(fluent = true) // generate fluent accessors with lombok and java-bean-style-accessors in non-abstract classes
// with ide, fluent accessors will (usually / by default) be ignored by mapstruct
public class TaskGroupBean implements TaskGroupEntity<TaskBean>
{
	@Nullable private Long  id;
	@Nullable private Short version;

	/** mutable non-null */
	// no lombok-generation of setter because of additional validation in manually created method
	@Setter(AccessLevel.NONE)
	@NonNull  private String name;

	/** mutable nullable */
	@Nullable private String description;

	/**
	 * prevent direct access to this modifiable set from outside this class, use {@link #addTask(TaskBean)} and
	 * {@link #removeTask(TaskBean)} to modify the set
	 * <p>
	 * may explicitly be {@code null}, {@code null} indicates that there was no attempt to load related objects from db
	 * (lazy)
	 */
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@Getter(AccessLevel.NONE) // provide handmade getter that returns unmodifiable
	@Setter(AccessLevel.NONE) // no setter at all
	@Nullable private Set<TaskBean> tasks;

	///////////////
	// constructors
	///////////////

	public TaskGroupBean(@NonNull String name) { name(name); }

	////////////////////////////////////////////////////////////////////////
	// fluent style accessors generated by lombok if not specified otherwise
	////////////////////////////////////////////////////////////////////////

	/**
	 * manually created fluent setter with extra parameter check (see throws documentation)
	 * @param name non-null, non-empty, non-blank
	 * @return {@code this}
	 * @throws IllegalArgumentException if {@code name} parameter is empty or blank
	 * @throws NullPointerException     if {@code name} parameter is {@code null}
	 */
	@Override @NonNull public TaskGroupBean name(@NonNull String name)
	{
		if (Strings.isEmptyOrBlank(name)) throw new IllegalArgumentException("name must not be empty nor blank");
		this.name = name;
		return this;
	}

	@Override @NonNull public Optional<String> description() { return Optional.ofNullable(description); }

	/** @return optional unmodifiable */
	@Override public @NonNull Optional<Set<TaskBean>> tasks()
	{
		if (Objects.isNull(tasks)) return Optional.empty();
		return Optional.of(Collections.unmodifiableSet(tasks));
	}

	///////////////////////
	// additional accessors
	///////////////////////

	// --- none ---

	////////////////////////
	// relationship handling
	////////////////////////
	/**
	 * @param bean the {@link Task} to be added as predecessor
	 * @return {@code this}
	 */
	@Override public boolean addTask(@NonNull TaskBean bean)
	{
		if (nonNullTasks().add(bean))
		{
			// update bidirectional relation
			bean.taskGroup(this);
			return true;
		}
		return false;
	}

	@Override public boolean removeTask(@NonNull TaskBean bean)
	{
		return tasks().map(ts -> ts.remove(bean)).orElse(false);
	}

	//////////////////////
	// mapstruct callbacks
	//////////////////////

	@BeforeMapping void beforeMapping(@NonNull TaskGroupEntityDTO source)
	{
		id      = source.id     ();
		version = source.version();

		source.tasks().ifPresent
		(
				vs -> vs.forEach(v -> addTask(Mapper.INSTANCE.lookupOrCreate(v)))
		);
	}

	@AfterMapping  void afterMapping (@NonNull TaskGroupEntityDTO source) { }

	@NonNull public TaskGroupEntityDTO toDTOSource() { return Mapper.INSTANCE.map(this); }

	@BeforeMapping void beforeMapping(@NonNull TaskGroupFXBean source)
	{
		mapIdAndVersion(new EntitySimple(source));

//		name(source.name());
		source.tasks().ifPresent(vs -> vs.forEach(v -> addTask(MapperFX.INSTANCE.lookupOrCreate(v))));
	}

	@AfterMapping void afterMapping (@NonNull TaskGroupFXBean source) { }

	@NonNull public TaskGroupFXBean toFXSource() { return MapperFX.INSTANCE.map(this); }

	private class AbstractEntitySimple extends AbstractEntity<AbstractDTOSimple> { }
	private class AbstractDTOSimple    extends AbstractDTO<AbstractEntitySimple> { }
	private class EntitySimple         extends AbstractEntity<AbstractDTOSimple>
	{
		public EntitySimple(Entity<Long> entity) { super(entity); }
	}
}