package de.ruu.app.jeeeraaah.client.fx.taskgroup;

import de.ruu.app.jeeeraaah.client.fx.taskgroup.editor.TaskGroupEditor;
import de.ruu.app.jeeeraaah.client.rs.ClientTaskGroup;
import de.ruu.app.jeeeraaah.common.TaskGroup;
import de.ruu.app.jeeeraaah.common.dto.TaskGroupDTO;
import de.ruu.lib.fx.comp.DefaultFXCViewController;
import de.ruu.lib.jpa.core.Entity;
import jakarta.enterprise.inject.spi.CDI;
import jakarta.inject.Inject;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.DialogPane;
import javafx.scene.control.TableView;
import javafx.scene.control.ToolBar;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

import java.util.Optional;

import static javafx.scene.control.ButtonBar.ButtonData.OK_DONE;
import static javafx.scene.control.ButtonType.CANCEL;
import static javafx.scene.control.ButtonType.OK;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.10.12 07:54:38:618
 */
@Slf4j
class TaskGroupManagementController extends DefaultFXCViewController implements TaskGroupManagementService
{
	static class TaskGroupFXBeanWithEntityInfo extends TaskGroupFXBean
	{
		private Entity.EntityInfo<Long> info;

		private TaskGroupFXBeanWithEntityInfo(@NonNull TaskGroup taskGroup)
		{
			super(taskGroup);
			info = new Entity.EntityInfo<>((Entity<Long>) taskGroup);
		}
	}

	@FXML private Button btnAdd;
	@FXML private Button btnEdit;
	@FXML private Button btnExit;
	@FXML private Button btnRemove;

	@FXML private ImageView ivwAdd;
	@FXML private ImageView ivwEdit;
	@FXML private ImageView ivwRemove;
	@FXML private ImageView ivwExit;

	@FXML private AnchorPane root;
	@FXML private ToolBar tbr1;
	@FXML private ToolBar tbr2;
	@FXML private TableView<TaskGroupFXBeanWithEntityInfo> tv;
	@FXML private VBox vbx;

	@Inject private ClientTaskGroup client;

	@Inject private TaskGroupEditor editor;

	@Override @FXML protected void initialize()
	{
		btnAdd .setOnAction(e -> onAdd (e));
		btnExit.setOnAction(e -> onExit(e));
	}

	private void onAdd(ActionEvent e)
	{
		TaskGroupFXBean taskGroupFXBean = new TaskGroupFXBean();

		// populate editor with new item
		editor.getService().taskGroup(taskGroupFXBean);

		Dialog<TaskGroupFXBean> dialog = new Dialog<>();

		DialogPane pane = dialog.getDialogPane();
		pane.setContent(editor.getLocalRoot());
		pane.getButtonTypes().addAll(CANCEL, OK);

		dialog.setTitle("new");
		dialog.setResultConverter(btn -> dialogResultConverterFXBean(btn));

		Optional<TaskGroupFXBean> optional = dialog.showAndWait();

		if (optional.isPresent())
		{
			// to create a new item in db the fx bean data has to be passed to
			TaskGroupDTO taskGroupDTO = client.create(taskGroupFXBean.toSource());

			TaskGroupFXBeanWithEntityInfo newItem = new TaskGroupFXBeanWithEntityInfo(taskGroupDTO);

			// add and select item with retrieved item
			tv.getItems().add(newItem);
			tv.getSelectionModel().select(newItem);
		}
	}

	private void onExit(ActionEvent e)
	{
		CDI.current().getBeanManager().getEvent().fire(new TaskGroupManagementDisposeRequestEvent(this));
	}

	private TaskGroupFXBean dialogResultConverterFXBean(ButtonType btn)
	{
		if (btn.getButtonData() == OK_DONE)
				return editor.getService().taskGroup().orElse(null);
		return null;
	}
}