package de.ruu.app.jeeeraaah.client.fx.taskgroup;

import de.ruu.app.jeeeraaah.common.Task;
import de.ruu.app.jeeeraaah.common.TaskGroup;
import javafx.beans.property.SetProperty;
import javafx.beans.property.SimpleSetProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;

import java.util.Optional;

/**
 * FXBean {@link TaskGroupFXBean}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.bean.FXBeanGenerator} at 2024.10.12 12:36:44:989
 */
@RequiredArgsConstructor
@Builder
@Getter
@Accessors(fluent = true)
public class TaskGroupFXBean
{
	private StringProperty    name  = new SimpleStringProperty();
	private SetProperty<Task> tasks = new SimpleSetProperty<> ();

	public TaskGroupFXBean(TaskGroup taskGroup)
	{
		name = new SimpleStringProperty(taskGroup.name());
		taskGroup.tasks().ifPresent(tasks -> tasks.addAll(tasks));
	}
	
	public @NonNull TaskGroup toSource() { return new TaskGroupBean(name.getValue(), Optional.of(tasks)); }
}