package de.ruu.app.jeeeraaah.client.fx.taskgroup;

import de.ruu.app.jeeeraaah.common.Task;
import de.ruu.app.jeeeraaah.common.TaskGroup;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NonNull;

import java.util.Optional;
import java.util.Set;

/**
 * JavaBean {@link TaskGroupBean}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.bean.BeanGenerator} at 2024.10.12 12:36:44:758
 */
@AllArgsConstructor
@Builder(toBuilder = true)
public class TaskGroupBean implements TaskGroup
{
	@NonNull private String name;
	@NonNull private Optional<Set<Task>> tasks;

	public TaskGroupBean(@NonNull TaskGroup taskGroup)
	{
		name  = taskGroup.name();
		tasks = taskGroup.tasks();
	}

	public String name()
	{
		return name;
	}
	
	public Optional<Set<Task>> tasks()
	{
		return tasks;
	}
}