package de.ruu.app.jeeeraaah.client.fx.task.editor;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.10.06 11:23:46:768
 */
class TaskEditorController extends DefaultFXCViewController
{
	@Override @FXML
	protected void initialize()
	{
	}
}