package de.ruu.app.jeeeraaah.client.fx.task.editor;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskEditorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.10.06 11:23:46:773
 */
@Slf4j class TaskEditorAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting TaskEditorAppRunner.class.getName()");
		FXCAppRunner.run(TaskEditorApp.class, args);
		log.debug("finished TaskEditorAppRunner.class.getName()");
	}
}