package de.ruu.app.jeeeraaah.client.fx.task.editor;

import de.ruu.lib.fx.comp.FXCViewService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.10.06 11:23:46:766
 */
public interface TaskEditorService extends FXCViewService
{
}