package de.ruu.app.demo.client.datamodel.fx;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link MainAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.07.06 10:42:19:793
 */
@Slf4j
class MainAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting MainAppRunner.class.getName()");
		FXCAppRunner.run(MainApp.class, args);
		log.debug("finished MainAppRunner.class.getName()");
	}
}