package de.ruu.app.demo.client.datamodel.fx;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.DefaultFXCViewController;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import jakarta.inject.Inject;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.TilePane;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.07.06 10:42:19:741
 */
@Slf4j
class MainController extends DefaultFXCViewController
{
	@FXML private Button btnAddresses;

	@FXML private Button btnExit;

	@FXML private AnchorPane root;
	@FXML private AnchorPane main;

	@FXML private TilePane tpn;

	@Inject private EventDispatcher<FXCAppStartedEvent> eventDispatcherFXCAppStarted;

	@Override @FXML
	protected void initialize()
	{
	}
}