package de.ruu.app.demo.client.datamodel.fx;

import de.ruu.lib.fx.comp.DefaultFXCViewController;
import javafx.fxml.FXML;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.07.06 10:42:19:741
 */ class MainController extends DefaultFXCViewController
{
	@Override @FXML
	protected void initialize()
	{
	}
}